import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio of Rubait Reshad",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark" data-color-mode="dark">
      <body className={inter.className}>
        <main className="bg-[#18181B]">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
